services:
  db: 
    image: postgres:16
    container_name: orientation_tests_db
    env_file:
      - .env.local
    ports: 
       - "5432:5432"
    volumes: 
      - postgres_data:/var/lib/postgresql/data
  
volumes:
  postgres_data: