services:
  db: 
    image: postgres:16
    container_name: orientation_tests_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports: 
       - "5432:5432"
    volumes: 
      - postgres_data:/var/lib/postgresql/data
  
volumes:
  postgres_data: